#ifndef CONSTANTES_H
#define CONSTANTES_H

#define QUANTIDADE_SALAS 3
#define QUANTIDADE_FILEIRAS 40
#define QUANTIDADE_POLTRONAS 10

#define MAX_INGRESSOS 400

#define PRECO_INTEIRA 20.00
#define PRECO_MEIA 10.00
#define PRECO_ITASIL 14.00

#define ARQUIVO_CINEMA "cinema.bin"

#endif